# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MissionaryTrainingApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MissionaryTrainingApp
  pod 'AppCenter/Crashes', '~> 1.5.0'
  pod 'AppCenter/Analytics', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'

  

  platform :ios, '9.0'
  pod 'RNAWSCognito', :path => '../node_modules/amazon-cognito-identity-js'

end
